### ISSUE TITLE
Furigana will be copied together with text

### ISSUE THREAD

**Issue by kirayomato** [larvata/miri-furigana#17]
I have used [Hide furigana on selecting], but the furigana is still copied together when copying. Even when I turn off the extension in the panel, it will still be copied.
The only way to solve this problem is to disable the extension completely in Chrome

**Comment by larvata** [comment]
bug occurs on copying tweet text with emoji

**Comment by larvata** [comment]
fixed in version 1.2.1

thank you for reporting the bug
